version: '3'
services:
  app:
    image: articles
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /src/main/resources/certificates

  database:
    image: 'postgres:15.5'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=books
      - POSTGRES_PASSWORD=root
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data