apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapp-v1
  labels:
    app-label: mainapp-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app-label: mainapp-v1
  template:
    metadata:
      labels:
        app-label: mainapp-v1
    spec:
      containers:
      - name: mainapp-v1
        image: cr.yandex/crpsdee4cj9f5r7k87ic/mainapp:v1
        env:
        - name: PORT
          value: "5432"
        - name: DATABASE_HOST
          value: "localhost"
        - name: POSTGRES_DB
          value: "books"
        - name: USER
          value: "postgres"
        - name: PASSWORD
          value: "root"