apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyckloak
  labels:
    app-label: keyckloak
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app-label: keyckloak
  template:
    metadata:
      labels:
        app-label: keyckloak
    spec:
      containers:
        - name: keyckloak-v1
          image: cr.yandex/crpsdee4cj9f5r7k87ic/keycloak:v1
          env:
            - name: DB_VENDOR
              value: "POSTGRES"
            - name: DB_ADDR
              value: "postgres"
            - name: DB_DATABASE
              value: "keycloakdb"
            - name: DB_SCHEMA
              value: "public"
            - name: DB_USER
              value: "keycloakuser"
            - name: DB_PASSWORD
              value: "keycloakpass"