apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpostgres
  labels:
    app-label: bpostgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app-label: bpostgres
  template:
    metadata:
      labels:
        app-label: bpostgres
    spec:
      containers:
        - name: bpostgres-v1
          image: cr.yandex/crpsdee4cj9f5r7k87ic/beverpostgres:v1
          env:
            - name: PORT
              value: "6432"
            - name: DATABASE_HOST
              value: "rc1a-7hralt7zq1xy378o.mdb.yandexcloud.net"
            - name: USER
              value: "beavers"
            - name: PASSWORD
              value: "beavers123"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"